# Generated by Django 4.2 on 2025-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='event_type',
            field=models.CharField(choices=[('Acesso', 'Acesso'), ('Download', 'Download')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
