# Generated by Django 4.2 on 2025-04-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_manager', '0002_downloadlog_event_type_alter_downloadlog_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='event_type',
            field=models.CharField(choices=[('Acesso', 'Acesso'), ('Visualização', 'Visualização'), ('Download', 'Download')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
