# Generated by Django 4.2.21 on 2025-05-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_manager', '0003_alter_downloadlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
