# Generated by Django 4.2 on 2025-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_manager', '0004_alter_downloadlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
