# Generated by Django 4.2.21 on 2025-05-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('drive_manager', '0006_permissaousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissaousuario',
            old_name='acesso_consulta',
            new_name='acesso_civv',
        ),
        migrations.AddField(
            model_name='permissaousuario',
            name='acesso_cipp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PermissaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_civv', models.BooleanField(default=True)),
                ('acesso_cipp', models.BooleanField(default=True)),
                ('pode_baixar', models.BooleanField(default=True)),
                ('acesso_logs', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
