# Generated by Django 4.2.21 on 2025-05-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive_manager', '0008_alter_permissaousuario_acesso_civv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissaogrupo',
            old_name='acesso_civv',
            new_name='acesso_civ',
        ),
        migrations.RenameField(
            model_name='permissaousuario',
            old_name='acesso_civv',
            new_name='acesso_civ',
        ),
    ]
